GetUser:
  handler: ./src/handlers/users/User.getUsersHandler
  events:
    - httpApi:
        path: /user
        method: get

AddUser:
  handler: ./src/handlers/users/User.addUserHandler
  events:
    - httpApi:
        path: /adduser
        method: post
